version: '3'
name: database
services: 
  mariadb:
    container_name: db_mariadb
    image: mariadb:10.7.8-focal
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - ./private/mariadb.env
    ports:
      - 3306:3306
    networks:
      - database
    restart: always
  
  phpmyadmin:
    container_name: db_pma
    image: phpmyadmin:apache
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=100M
      - PMA_ABSOLUTE_URL=http://localhost/phpmyadmin/
    ports:
      - 1000:80
    links:
      - mariadb:db
    networks:
      - database
      - environment
    restart: always

volumes:
  mariadb_data:
    name: mariadb_data

networks:
  database:
    driver: bridge
    name: database
  
  environment:
    name: environment
    external: true