version: '3'
name: database
services: 
  mariadb:
    container_name: db_mariadb
    image: mariadb:10.7.8-focal
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - ./private/mariadb.env
    ports:
      - 3306:3306
    networks:
      - database
  
  phpmyadmin:
    container_name: db_pma
    image: phpmyadmin:apache
    depends_on:
      - mariadb
    env_file:
      - ./private/pma.env
    links:
      - mariadb:db
    networks:
      - database

volumes:
  mariadb_data:
    name: mariadb_data

networks:
  database:
    driver: bridge
    name: database